# -*- coding: utf-8 -*-
"""Python Assesment 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w9V4mPsvQgfgbRPypvEJ2oXZVdmxc6Wr
"""

#Assesment 1

""" 1) Import pandas and read in the banklist.csv file into a dataframe called
banks."""
import pandas as pd
Banks = pd.read_csv("banklist.csv")
Banks

#2. Show the head of the dataframe.

Banks = pd.read_csv("banklist.csv")
print(Banks.head())

#3. What are the column names?

print("colomn name :",Banks.columns.tolist())

#4. How many States (ST) are represented in this data set?
print("number of state :",Banks["ST"].nunique())

#5. Get a list or array of all the states in the data set.

print("list of state :",Banks["ST"].unique())

#6. What are the top 5 states with the most failed banks?
print("Top 5 states with most failed banks :",Banks["ST"].value_counts().head(5))

#7. What are the top 5 acquiring institutions?
print("top 5 acquiring institutions :",Banks["Acquiring Institution"].value_counts().head(5))

"""8. How many banks has the State Bank of Texas acquired? How many of
them were actually in Texas?"""

california_failures = Banks[Banks['ST'] == 'CA']
most_common_city_ca = california_failures['City'].value_counts().index[0]
print(f"\nMost Common City in California for Bank Failures: {most_common_city_ca}")

#9. What is the most common city in California for a bank to fail in?


state_bank_tx_acquisitions = Banks[Banks['Acquiring Institution'] == 'State Bank of Texas']
total_acquisitions = len(state_bank_tx_acquisitions)
texas_acquisitions = len(state_bank_tx_acquisitions[state_bank_tx_acquisitions['ST'] == 'TX'])

print(f"\nState Bank of Texas Total Acquisitions: {total_acquisitions}")
print(f"State Bank of Texas Acquisitions in Texas: {texas_acquisitions}")