# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GYFCdAXbI9x0NOaPn5mq-BDRsK8YhO0N
"""

# Assesment 2

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

rr = pd.read_csv("histo_automobile_sales.csv")
rr

"""Q 1: Develop a Line chart using the functionality of pandas to show how
automobile sales fluctuate from year to year."""

plt.figure(figsize=(10, 6))
plt.plot(rr['Year'], rr['Automobile_Sales'])
plt.title('Automobile Sales Fluctuation Over Years')
plt.xlabel('Year')
plt.ylabel('Total Sales')
plt.grid(True)
plt.show()

"""Q 2: Plot different lines for categories of vehicle type and analyze the trend
to answer the question Is there a noticeable difference in sales trends
between different vehicle types during recession periods?"""

vehicle_types = rr['Vehicle_Type'].unique()

plt.figure(figsize=(12, 8))
for vehicle in vehicle_types:
    vehicle_data = rr[rr['Vehicle_Type'] == vehicle]
    vehicle_sales_yearly = vehicle_data.groupby('Year')['Automobile_Sales'].sum().reset_index()
    plt.plot(vehicle_sales_yearly['Year'], vehicle_sales_yearly['Automobile_Sales'], label=vehicle)


recession_years = rr[rr['Recession'] == True]['Year'].unique()
for year in recession_years:
    plt.axvspan(year - 0.5, year + 0.5, color='red', alpha=0.2, label='Recession' if year == recession_years[0] else "") # Only label once

plt.title('Sales Trends by Vehicle Type and Recession Periods')
plt.xlabel('Year')
plt.ylabel('Sales')
plt.legend()
plt.grid(True)
plt.show()

"""Q 3: Use the functionality of Seaborn Library to create a visualization to compare
the sales trend per vehicle type for a recession period with a non- recession
period."""

plt.figure(figsize=(14, 8))
sns.lineplot(x='Year', y='Automobile_Sales', hue='Vehicle_Type', style='Recession', data=rr, estimator='sum', errorbar=None)
plt.title('Sales Trend Comparison: Recession vs. Non-Recession by Vehicle Type')
plt.xlabel('Year')
plt.ylabel('Sales')
plt.grid(True)
plt.show()

"""Q 4: Now you want to compare the sales of different vehicle types
during a recession and a non-recession period"""
sales_comparison = rr.groupby(['Recession', 'Vehicle_Type'])['Automobile_Sales'].sum().reset_index()


plt.figure(figsize=(12, 8))
sns.barplot(x='Vehicle_Type', y='Automobile_Sales', hue='Recession', data=sales_comparison)
plt.title('Comparison of Vehicle Sales: Recession vs. Non-Recession')
plt.xlabel('Vehicle Type')
plt.ylabel('Total Sales')
plt.legend(title='Recession')
plt.grid(axis='y')
plt.show()

